### ISSUE TITLE
Manually add styles?

### ISSUE THREAD

**Issue by pivic** [marcusolsson/obsidian-vale#11]
I just discovered [Openly](https://github.com/testthedocs/Openly), the Vale linter style.

I know that Openly is mentioned in [this obsidian-vale conversation](https://github.com/marcusolsson/obsidian-vale/issues/5), but until Openly is possibly added to obsidian-vale, it sparked a question:

Is it possible to manually add styles to obsidian-vale?

I downloaded and copied the Openly folder (that contains Vale-formatted .yml files) to the **.obsidian/plugins/obsidian-vale/data/styles** folder, restarted Obsidian, tried to check plugin settings, even tried to run the plugin again, but it seems not to trigger anything.

I'm definitely not a developer and don't have the skills required to troubleshoot this; it could very well be that the Openly files aren't compatible with obsidian-vale, but still...

**Comment by marcusolsson** [comment]
In addition to downloading the style to the styles directory, you also need to enable it in the .vale.ini file:

```
BasedOnStyles = Openly
```

It shouldn't interfere with any of the built-in styles, but let me know if it does.

**Comment by pivic** [comment]
@marcusolsson: thanks a lot! That worked perfectly!
