### ISSUE TITLE
Question: method to check grammar

### ISSUE THREAD

**Issue by ms3056** [marcusolsson/obsidian-vale#5]
Hi - thank you for creating this tool. I am hoping you can point me to a way to have grammar checked - for instance the following sentence: "This is sentence that suck." This is not flagged with any of the linters that I am able to install (Google, Microsoft, prolint). 

Thank you for your help, I realize this is not an issue at all with your plugin - it works beautifully.

**Comment by dylan-k** [comment]
There's a vale style called [Openly](https://github.com/testthedocs/Openly) that's designed to be an open-source, vale-compatible alternative to Grammarly.

**Comment by marcusolsson** [comment]
Added Openly in https://github.com/marcusolsson/obsidian-vale/commit/47ca1db9432d382459638514cd8de674d2c037d9. Will be part of next release.

**Comment by marcusolsson** [comment]
This is now available in v0.9.0 🚀
