### ISSUE TITLE
Feature Request: Toggle the Editorial Marks' Visibility 

### ISSUE THREAD

**Issue by dylan-k** [marcusolsson/obsidian-vale#8]
I'm so excited to have this plugin. Thank you for making it.

I have a request for a feature that could be helpful. It seems that once I've checked an Obsidian document with vale, there's no way to hide the marks it makes for errors and suggestions. Could there be a way to toggle these? Sometimes I shift between editing and writing modes and it's helpful to remove distractions during the writing mode. Could there be a feature to toggle the marks off and on?

**Comment by marcusolsson** [comment]
I don't see why not :) Would a command work, like "Vale: Toggle check results"?

**Comment by dylan-k** [comment]
Yes @marcusolsson  I think a command like "Vale: Toggle Check Results" would work perfectly. 

(Congrats by the way on the [Obsidian October](https://obsidian.md/october2021) honorable mention!)

**Comment by marcusolsson** [comment]
Thanks! Think I could get this released during the weekend.

**Comment by marcusolsson** [comment]
This is now available in v0.9.0 🚀
